localisort -t ./layout/Library/Application\ Support/SafariPlus.bundle/en.lproj/Localizable.strings -i ./layout/Library/Application\ Support/SafariPlus.bundle/ar.lproj/Localizable.strings -r
localisort -t ./layout/Library/Application\ Support/SafariPlus.bundle/en.lproj/Localizable.strings -i ./layout/Library/Application\ Support/SafariPlus.bundle/de.lproj/Localizable.strings -r
localisort -t ./layout/Library/Application\ Support/SafariPlus.bundle/en.lproj/Localizable.strings -i ./layout/Library/Application\ Support/SafariPlus.bundle/es.lproj/Localizable.strings -r
localisort -t ./layout/Library/Application\ Support/SafariPlus.bundle/en.lproj/Localizable.strings -i ./layout/Library/Application\ Support/SafariPlus.bundle/fr.lproj/Localizable.strings -r
localisort -t ./layout/Library/Application\ Support/SafariPlus.bundle/en.lproj/Localizable.strings -i ./layout/Library/Application\ Support/SafariPlus.bundle/it.lproj/Localizable.strings -r
localisort -t ./layout/Library/Application\ Support/SafariPlus.bundle/en.lproj/Localizable.strings -i ./layout/Library/Application\ Support/SafariPlus.bundle/ru.lproj/Localizable.strings -r
localisort -t ./layout/Library/Application\ Support/SafariPlus.bundle/en.lproj/Localizable.strings -i ./layout/Library/Application\ Support/SafariPlus.bundle/tr.lproj/Localizable.strings -r
localisort -t ./layout/Library/Application\ Support/SafariPlus.bundle/en.lproj/Localizable.strings -i ./layout/Library/Application\ Support/SafariPlus.bundle/zh-Hans.lproj/Localizable.strings -r
localisort -t ./layout/Library/Application\ Support/SafariPlus.bundle/en.lproj/Localizable.strings -i ./layout/Library/Application\ Support/SafariPlus.bundle/zh-Hant.lproj/Localizable.strings -r
localisort -t ./layout/Library/Application\ Support/SafariPlus.bundle/en.lproj/Localizable.strings -i ./layout/Library/Application\ Support/SafariPlus.bundle/pt-br.lproj/Localizable.strings -r
